Metrics/LineLength:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/PredicateName:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
