language: ruby
sudo: false
cache: bundler
script: 'bundle exec rubocop && bundle exec rake test:coverage --trace'
after_script: 'echo `env`'
rvm:
  - 2.3.1
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head
env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

addons:
  postgresql: '9.4'

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
