language: ruby
sudo: false
cache: bundler
install: true
script:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION; fi'
  - 'bundle install'
  - 'bundle exec rake test:coverage'
rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9000
  - jruby-head

addons:
  postgresql: '9.4'

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
