language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace'
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head
env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

addons:
  postgresql: '9.4'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: "DB=mysql"
      rvm: jruby-9.0.5.0
